version: 0.0
os: linux
files:
  - source: /
    destination: /bmi
permissions:
  - object: /bmi
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
