#!/bin/bash

# Make sure you replace 'your_secret_name' and 'your_aws_region' with the actual secret name and AWS region
secret=$(aws secretsmanager get-secret-value --secret-id bmi-calculator --region ca-central-1 --query SecretString --output text)

# Parse the JSON and write each key-value pair as "KEY=VALUE" into .env
echo $secret | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > /app/.env
