#!/bin/bash
# Update package lists for upgrades and new package installations
apt-get update -y
apt-get install -y awscli
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
apt-get install -y nodejs
apt-get install -y npm
npm install -g pm2
apt-get install -y jq
if [ -d "/app" ]; then
  rm -R /app
fi
